### ISSUE TITLE
Odhady pro vytvoření prototypu

### ISSUE THREAD

**Issue by pepe** [LastStar/zackoviny#2]
Diskuze odhadu pro vytvoření prototypu

**Comment by quirm** [comment]
HTML vidim na 20h~ s tim hotovym drag/drop a jeste tam pridam tu hadanku a nejake okna s napovedou, pokud pribude 3. stranka jineho typu tak dalsi hodinku/ny navic podle slozitosti.

**Comment by pepe** [comment]
Poprosil bych ještě iOS odhad

/cc @eskimag

**Comment by pepe** [comment]
A ještě kolik odhadem v tom máš @quirm času teď?

**Comment by quirm** [comment]
Teď to bude skoro už přes, ale dejme tomu že 20h je pro dokončení toho co jsem tam napsal bez 3. stránky.

**Comment by stefanluptak** [comment]
Ahojte, ja som ešte na Slovensku a dnes už som mimo, ale zajtra doobeda (dopoledne) sa k tomu vyjadrím, keď si popozerám všetky tie maily atď.

**Comment by stefanluptak** [comment]
@pepe takže môj odhad je 15 hodín.
