### ISSUE TITLE
Nápady, aneb co kdo najdete

### ISSUE THREAD

**Issue by pepe** [LastStar/zackoviny#4]
Tak první věc: http://www.gabrielweinberg.com/blog/2011/04/toddler-app-user-interface-guidelines.html

**Comment by pepe** [comment]
prej nejlepší knížka pro iPad http://itunes.apple.com/us/app/the-fantastic-flying-books/id438052647?mt=8&ign-mpt=uo%3D4

**Comment by quirm** [comment]
ceska verze casopisu Slunicko http://itunes.apple.com/cz/app/id445818096?mt=8
udelali uplne totez co se snazime my, jen vyuzivaji licensovany framework pro nacitani obsahu, je tam spousta veci cim se inspirovat a take co udelat lepe v nasi verzi

**Comment by pepe** [comment]
Koukal jsem na to, tedy zatím jen v iTunes. Dobrá trefa, to chce okopírovat. Nevíš kolik ta license stojí?

**Comment by quirm** [comment]
$2500 koupit uvodni na 5 mesicu a pak kazde dalsi issue $500

pro: 
- pouzijes tendle template ktery je pouzit ve vice nez 100 magazinu (national geographic, wired, formen - mafra, popscience, atd.), bude to uzivatelsky asi ovladatelne
- cena vypada mala v porovnani s vyvojem co na to das

proti:
- je to hnus UI, grafika, je to okoukane a ma to kazdy tj ze neprijdes s nicim novym
- jsme limitovani moznostmi templatu
